name: Website Publish

on:
  push:
    branches: [ master ]

jobs:
  publish-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npx @serverless-devs/s config add --AccountID a --AccessKeyID b --AccessKeySecret c -a default
      - run: npx @serverless-devs/s deploy